const jobDescriptions = {
  fullStackDeveloper: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Redux",
    "Next.js",
    "Node.js",
    "Express.js",
    "MongoDB",
    "MySQL",
    "REST API",
    "JWT",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "Linux",
    "CI/CD",
    "Problem Solving",
  ],

  frontendDeveloper: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Redux",
    "Next.js",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Responsive Design",
    "Webpack",
    "Vite",
    "Git",
    "GitHub",
    "REST API",
    "UI/UX",
    "Problem Solving",
  ],

  backendDeveloper: [
    "Node.js",
    "Express.js",
    "NestJS",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Redis",
    "REST API",
    "GraphQL",
    "JWT",
    "Docker",
    "AWS",
    "Linux",
    "Git",
    "GitHub",
    "CI/CD",
    "Microservices",
    "Problem Solving",
  ],

  devopsEngineer: [
    "Docker",
    "Kubernetes",
    "OpenShift",
    "Tekton",
    "Jenkins",
    "Terraform",
    "Ansible",
    "AWS",
    "Azure",
    "Linux",
    "Shell Scripting",
    "CI/CD",
    "Git",
    "GitHub",
    "Prometheus",
    "Grafana",
    "Nginx",
    "Problem Solving",
  ],

  cloudEngineer: [
    "AWS",
    "Azure",
    "Google Cloud",
    "EC2",
    "S3",
    "Lambda",
    "IAM",
    "CloudFormation",
    "CloudWatch",
    "Docker",
    "Kubernetes",
    "Linux",
    "Terraform",
    "Git",
    "CI/CD",
  ],

  dataEngineer: [
    "Python",
    "SQL",
    "PostgreSQL",
    "MongoDB",
    "Apache Spark",
    "Kafka",
    "Hadoop",
    "Airflow",
    "ETL",
    "Data Warehousing",
    "Snowflake",
    "Big Data",
    "Data Pipeline",
    "AWS",
    "Git",
  ],

  aiEngineer: [
    "Python",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Generative AI",
    "OpenAI",
    "ChatGPT",
    "LangChain",
    "Prompt Engineering",
    "RAG",
    "Vector Database",
    "Embeddings",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "NLP",
    "Computer Vision",
    "Git",
  ],

  mobileDeveloper: [
    "React Native",
    "Flutter",
    "Android",
    "iOS",
    "Swift",
    "Kotlin",
    "Expo",
    "REST API",
    "Firebase",
    "Git",
    "GitHub",
    "Mobile Development",
  ],
  technicalSpecialist: [
    "JavaScript",
    "Node.js",
    "MongoDB",
    "Git",
    "GitHub",
    "Docker",
    "Kubernetes",
    "OpenShift",
    "CI/CD",
    "Google Cloud",
    "Technical Support",
    "Troubleshooting",
    "Problem Solving",
    "Communication",
    "Leadership",
    "Collaboration",
    "Content Development",
    "Documentation",
    "API Testing",
    "Postman",
    "Linux",
    "DevOps",
    "Learner Support",
    "Customer Support",
    "Training",
    "Mentoring",
    "Technical Writing",
  ],
};

module.exports = jobDescriptions;
