const skillsDatabase = {
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Redux",
    "Next.js",
    "Angular",
    "Vue.js",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "SASS",
    "SCSS",
    "jQuery",
    "Responsive Design",
    "Webpack",
    "Vite",
    "PWA",
    "UI/UX",
  ],

  backend: [
    "Node.js",
    "Express.js",
    "NestJS",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Java",
    "Spring Boot",
    "PHP",
    "Laravel",
    ".NET",
    "C#",
    "Ruby on Rails",
    "REST API",
    "GraphQL",
    "WebSocket",
    "Microservices",
    "Serverless",
    "MVC",
  ],

  databases: [
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Oracle",
    "Redis",
    "Firebase",
    "DynamoDB",
    "Cassandra",
    "MariaDB",
    "Mongoose",
    "Prisma",
    "Sequelize",
    "Database Design",
    "SQL",
  ],

  devops: [
    "Docker",
    "Kubernetes",
    "OpenShift",
    "Tekton",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI/CD",
    "Terraform",
    "Ansible",
    "Helm",
    "Prometheus",
    "Grafana",
    "Nginx",
    "Apache",
    "CI/CD",
    "Linux",
    "Bash",
    "Shell Scripting",
  ],

  cloud: [
    "AWS",
    "Azure",
    "Google Cloud",
    "EC2",
    "S3",
    "Lambda",
    "CloudFormation",
    "CloudWatch",
    "ECS",
    "EKS",
    "RDS",
    "IAM",
    "Cloud Run",
    "BigQuery",
    "Firebase Hosting",
  ],

  testing: [
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "JUnit",
    "PyTest",
    "Unit Testing",
    "Integration Testing",
    "E2E Testing",
    "API Testing",
    "Postman",
    "Load Testing",
  ],

  ai_ml: [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Generative AI",
    "LLM",
    "OpenAI",
    "ChatGPT",
    "LangChain",
    "Prompt Engineering",
    "RAG",
    "Vector Database",
    "Embeddings",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Hugging Face",
  ],

  mobile: [
    "React Native",
    "Flutter",
    "Android",
    "iOS",
    "Swift",
    "Kotlin",
    "Expo",
    "Mobile Development",
  ],

  security: [
    "JWT",
    "OAuth",
    "Authentication",
    "Authorization",
    "Cybersecurity",
    "OWASP",
    "HTTPS",
    "Encryption",
    "Hashing",
    "RBAC",
  ],

  dataEngineering: [
    "Apache Spark",
    "Kafka",
    "Hadoop",
    "Airflow",
    "ETL",
    "Data Warehousing",
    "Snowflake",
    "Data Pipeline",
    "Data Lake",
    "Big Data",
  ],

  fundamentals: [
    "Data Structures",
    "Algorithms",
    "Object Oriented Programming",
    "DBMS",
    "Operating Systems",
    "Computer Networks",
    "System Design",
    "Design Patterns",
    "Problem Solving",
    "Software Engineering",
  ],

  tools: [
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "VS Code",
    "Jira",
    "Confluence",
    "Figma",
    "Slack",
    "Notion",
  ],

  softSkills: [
    "Communication",
    "Leadership",
    "Teamwork",
    "Critical Thinking",
    "Time Management",
    "Agile",
    "Scrum",
    "Collaboration",
    "Mentoring",
    "Problem Solving",
  ],
};

module.exports = skillsDatabase;
